### ISSUE TITLE
a few #define is not correct

### ISSUE THREAD

**Issue by vmynick** [EasyG0ing1/BlockNot#13]
Hi there, 

The below part in BlockNot.h not looks correct.

#define STARTED                     running()
#define RUNNING                     running()
#define STOPPED                     stopped()

#define STOPPED                     isSstopped()

Rgds,  V.

**Comment by EasyG0ing1** [comment]
@vmynick - Hello,

Thank you for bringing this to my attention, you are absolutely correct. The last update was very labor-intensive with a bit of a learning curve for me so it doesn't surprise me that something fell through the cracks.

I fixed the problem and will be publishing a 1.8.3 update within the hour.

Thanks again!

Mike

**Comment by vmynick** [comment]
Thanks a lot.

Keep up the good work. :)

V.

**Comment by EasyG0ing1** [comment]
@vmynick - Thank you!
