### ISSUE TITLE
warning

### ISSUE THREAD

**Issue by prophetmaster** [EasyG0ing1/BlockNot#15]
your function is bool but not initialized the bool variable...

`.pio/libdeps/16Mb-ESP32-WROVER-IE-debug/BlockNot/src/BlockNot.cpp: In member function 'bool BlockNot::hasTriggered()':
.pio/libdeps/16Mb-ESP32-WROVER-IE-debug/BlockNot/src/BlockNot.cpp:543:12: warning: 'triggered' may be used uninitialized in this function [-Wmaybe-uninitialized]
     return triggered;
            ^~~~~~~~~
.pio/libdeps/16Mb-ESP32-WROVER-IE-debug/BlockNot/src/BlockNot.cpp: In member function 'bool BlockNot::hasNotTriggered()':
.pio/libdeps/16Mb-ESP32-WROVER-IE-debug/BlockNot/src/BlockNot.cpp:559:12: warning: 'notTriggered' may be used uninitialized in this function [-Wmaybe-uninitialized]
     return notTriggered;
            ^~~~~~~~~~~~
.pio/libdeps/16Mb-ESP32-WROVER-IE-debug/BlockNot/src/BlockNot.cpp: In member function 'bool BlockNot::triggeredOnDuration(bool)':
.pio/libdeps/16Mb-ESP32-WROVER-IE-debug/BlockNot/src/BlockNot.cpp:261:30: warning: 'missedDurations' may be used uninitialized in this function [-Wmaybe-uninitialized]
         totalMissedDurations += (allMissed ? missedDurations : 0);
         ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

``

**Comment by EasyG0ing1** [comment]
@prophetmaster 

I'm not sure what you mean when you say that it is not initialized the bool variable...

Based on the copied error that you provided, you might need to look at the syntax in your code and make sure that if you're using the method name outright, then don't forget the parentheses 

```myTimer.triggered()```

And if you chose to call that method using the macro, then you only use the macro name without parentheses:

```myTimer.TRIGGERED```

Text case matters specifically in this context ... the method name itself is all lowercase and the macro is all UPPERCASE.

As to the methods being declared as bool objects, the triggered() and hasTriggered() methods are declared in the header file like this:
```C++
bool triggered(bool resetOption = true);
bool notTriggered();
```
and in the `.cpp` file like this
```C++
bool BlockNot::triggered(bool resetOption) {
    bool triggered = hasTriggered();
    if (resetOption && triggered) {
        reset();
    }
    return timerState == RUNNING && triggered;
}

bool BlockNot::notTriggered() {
    return timerState == RUNNING && !hasTriggered();
}

```

So the methods are indeed declared as type `bool`

There are several ways to engage the methods as any of these will work just fine:
```C++
BlockNot myTimer (7000);

Loop() {
    if(myTimer.TRIGGERED) {
        //Run this code
    }

    if(myTimer.triggered()) {
        //Run this code
    }

    if(myTimer.NOT_TRIGGERED) {
        //Run this code
    }

    if(myTimer.notTriggered()) {
        //Run this code
    }
}
```
as well as other ways that you can engage the methods but those are the most common ways of engaging those methods.

**Comment by EasyG0ing1** [comment]
No response
